import { SUM } from "../utils/helpers.js";
import Task, { TaskPartSolution } from "../utils/task.js";

const part1: TaskPartSolution = (input) => {
  const [start, ...rows] = input.split("\n").map((line) => line.split(""));
  let positions = start.map((c) => c === "S");
  let splits = 0;
  rows.forEach((row) => {
    for (let i = 0; i < positions.length; i++) {
      if (positions[i]) {
        if (row[i] === "^") {
          splits++;
          positions[i] = false;
          positions[i - 1] = true;
          positions[i + 1] = true;
        }
      }
    }
    // console.log(positions.map((p) => (p ? "|" : ".")).join(""));
  });
  return splits;
};
const part2: TaskPartSolution = (input) => {
  const [start, ...rows] = input.split("\n").map((line) => line.split(""));
  let positions = start.map((c) => (c === "S" ? 1 : 0));
  rows.forEach((row) => {
    for (let i = 0; i < positions.length; i++) {
      if (positions[i] > 0) {
        if (row[i] === "^") {
          positions[i - 1] += positions[i];
          positions[i + 1] += positions[i];
          positions[i] = 0;
        }
      }
    }
  });
  return SUM(positions);
};

const task = new Task(2025, 7, part1, part2, {
  part1: {
    input: `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`,
    result: "21",
  },
  part2: {
    input: `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`,
    result: "40",
  },
});

export default task;
